# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: pirecorder documentation
email: j.w.jolles@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Detailed documentation for use of the python pirecorder package.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jollejolles.github.io/pirecorder/"
twitter_username: jollewjolles
github_username:  jollejolles

# Build settings
remote_theme:  pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

include:
  - _docs

# Theme settings
logo: "/assets/images/pirecorder-logo-small.png"
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "pirecorder on GitHub":
    - "//github.com/jollejolles/pirecorder"
heading_anchors: true
footer_content: "Copyright &copy; 2020 Jolle Jolles. pirecorder is released under an <a href=\"https://github.com/JolleJolles/pirecorder/blob/master/LICENSE\">Apache 2.0 license</a>. Website build using the <a href=\"https://github.com/pmarsceill/just-the-docs\">Just the Docs</a> theme.</a>"
